@create_user = http://127.0.0.1:8000/auth/users/
@get_token = http://127.0.0.1:8000/auth/jwt/create/
@posts = http://127.0.0.1:8000/api/v1/posts/
@post = http://127.0.0.1:8000/api/v1/posts/1/
@comments = http://127.0.0.1:8000/api/v1/posts/1/comments/
@comment = http://127.0.0.1:8000/api/v1/posts/1/comments/1/
@groups = http://127.0.0.1:8000/api/v1/groups/
@group = http://127.0.0.1:8000/api/v1/groups/1/
@follow = http://127.0.0.1:8000/api/v1/follow/

###
POST {{create_user}} HTTP/1.1
Content-Type: application/json

{
    "username": "apap",
    "password": "qwe123asddsa"
}

###
POST {{get_token}} HTTP/1.1
content-type: application/json

{
    "username": "apap",
    "password": "qwe123asddsa"
}

###
GET {{posts}} HTTP/1.1
content-type: application/json

###
GET {{post}} HTTP/1.1
content-type: application/json

###
POST {{posts}} HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjc3NDAwMzc4LCJqdGkiOiJiMzQxZmU2YTE5NTc0NDkzYjQ2Y2I0Mjk2ZGViYjg2YSIsInVzZXJfaWQiOjN9.NQTv1JDaMLlWm7Qex9jO49_aJpxIhGl7BjP5NzWB5Ps
content-type: application/json

{
    "text": "3й самый лучший пост в мире",
    "image": null
}

###
GET {{comments}} HTTP/1.1
content-type: application/json

###
GET {{comment}} HTTP/1.1
content-type: application/json

###
POST {{comments}} HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjc3Mzk5Mjg3LCJqdGkiOiI0NjJhNTk5YjdkMTU0Zjc4YWRkMTBhZGZlYmU3YjliZCIsInVzZXJfaWQiOjF9.m3UPY8S-EVQ30r8uXeFhLm7omEeoDH_C-97jfcU3Eso
content-type: application/json

{
    "text": "Тут должно быть что то интересное"
}

###
GET {{groups}} HTTP/1.1
content-type: application/json

###
GET {{group}} HTTP/1.1
content-type: application/json

###
GET {{follow}} HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjc3Mzk5Mjg3LCJqdGkiOiI0NjJhNTk5YjdkMTU0Zjc4YWRkMTBhZGZlYmU3YjliZCIsInVzZXJfaWQiOjF9.m3UPY8S-EVQ30r8uXeFhLm7omEeoDH_C-97jfcU3Eso
content-type: application/json

###
POST {{follow}} HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjc3Mzk5Mjg3LCJqdGkiOiI0NjJhNTk5YjdkMTU0Zjc4YWRkMTBhZGZlYmU3YjliZCIsInVzZXJfaWQiOjF9.m3UPY8S-EVQ30r8uXeFhLm7omEeoDH_C-97jfcU3Eso
content-type: application/json

{
    "following": "apap"
}